### PR TITLE
Include license and add changelog

### PR DESCRIPTION
**Pull request by wagner-certat**

### CODE REVIEW

**Comment by Fitblip** [comment]
Unless you can give me a good justification for why I need this PR I'm not going to merge it.

**Comment by wagner-certat** [comment]
The tarballs at pypi (https://pypi.python.org/pypi/certstream) don't include these files if you do not specify them in the file. Both files should be bundled together with the source code.

See also the Python Packaging tutorial:
https://packaging.python.org/tutorials/distributing-packages/#license-txt

And why a changelog is useful: Because then the users of this program, other developers using it in other projects and packagers can easily see what has changes and what they need to change in their applications, libraries and packages. Otherwise they do either not take note of relevant changes or need to browse the commit history.

**Comment by wagner-certat** [comment]
Any further comments on that?

**Comment by wagner-certat** [comment]
Also see http://keepachangelog.com/ and http://reuse.software/

**Comment by wagner-certat** [comment]
Would it be possible to include the license in the tarball?

**Comment by Fitblip** [comment]
Will do!

**Pull request closed without merging**
