### PR TITLE
Add http proxy support

### PR DESCRIPTION
**Pull request by Goblenus**
Now you can use http proxy :)

### CODE REVIEW

**Comment by Fitblip** [comment]
Ooh nice! Thanks for the PR, and great idea :)

I'm going to propose a counter-pr to yours that actually structures this a bit differently to essentially expose any of the `WebsocketApp.run_forever` method's arguments (by passing around kwargs instead of explicit arguments). The documentation/consumption should be the same and just allows one to override some other features (like the origin, or ssl configuration, etc).

**Comment by Goblenus** [comment]
Not sure, that this a better way to add note about `kwargs`.

**Comment by Fitblip** [comment]
Nice, maybe we should link to the function itself so they can see what options are available easily? 

https://github.com/websocket-client/websocket-client/blob/87861f951d1a65ed5d9080f7aaaf44310f376c56/websocket/_app.py#L169-L192

Cheers :)

**Comment by Goblenus** [comment]
I thought about that, and this is not good idea, because the function location may be changed and our url will be useless. But this is the best way to tell why and what for we use kwargs.

**Comment by Fitblip** [comment]
That URL is actually a permalink to that function args/docs at that specific commit, which of course means it won't be updated automatically, but it will be correct for some definition of correct which I think will suffice for our needs. 

The github permalink thing is also just another one of those neat github things that's not obvious, so in case you were wondering where I got it:
image

**Comment by Goblenus** [comment]
Wow...I didn't know about that, thanks. Can you add url and merge by yourself?

**Comment by Fitblip** [comment]
Sure! Just wanted to make sure you were cool with it :)

Thanks again for the PR!

**Pull request merged**
